sudo: false
language: python
cache: pip

addons:
    apt:
        packages:
            - cython
            - build-essential
            - liblircclient-dev
            - lirc
            - python3-dev

matrix:
    include:
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7-dev
          env: TOXENV=py37
        - python: 3.5
          env: TOXENV=qa

install: pip install --ignore-installed --upgrade setuptools pip tox Cython
script: tox -vv
